language: ruby
rvm:
  - 2.2.3
env:
  - DB=sqlite3
script:
  - bundle exec rake db:rollback
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec
  - rubocop -c ~/build/kevinegstorf/flix/.rubocop.yml
before_install:
  - gem update --system
  - gem install bundler
  - gem install rails
  - gem install pry
  - gem install rubocop
notifications:
  slack: railsdevkev:2Hc03EHDhMxN6F9bDx4pm3dJ
